# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_organizations', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Organization'), (1, 'School'), (2, 'Company'), (3, 'Group of volunteers')], default=0, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
