# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_core', '0004_load_skills_and_causes'),
        ('ovp_organizations', '0003_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='causes',
            field=models.ManyToManyField(to='ovp_core.Cause'),
        ),
    ]
