# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ovp_organizations', '0006_auto_20161206_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
