# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_organizations', '0009_organizationinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinvite',
            name='accepted_date',
        ),
        migrations.RemoveField(
            model_name='organizationinvite',
            name='created_date',
        ),
    ]
