# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_organizations', '0016_organization_hide_address'),
        ('ovp_organizations', '0016_auto_20170117_1952'),
    ]

    operations = [
    ]
