# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_organizations', '0017_merge_20170127_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='hide_address',
        ),
        migrations.AddField(
            model_name='organization',
            name='hidden_address',
            field=models.BooleanField(default=False, verbose_name='Hidden address'),
        ),
    ]
