# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_organizations', '0020_auto_20170412_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='details',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Details'),
        ),
    ]
