# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_organizations', '0023_auto_20170712_1704'),
        ('ovp_organizations', '0023_auto_20170627_0236'),
    ]

    operations = [
    ]
