# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_organizations', '0024_merge_20170712_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='atados_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovp_core.GoogleAddress', verbose_name='address'),
        ),
    ]
